# Generated by Django 3.2.7 on 2021-10-06 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('takeaway', models.BooleanField(default=False)),
                ('delivery', models.PositiveIntegerField(choices=[(0, '0'), (500, '500'), (1000, '1000'), (1500, '1500')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=40)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('item_price', models.PositiveIntegerField()),
                ('double_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('meal_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('double_meal_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread', models.PositiveIntegerField(choices=[(0, 'خبز'), (700, 'مقرنات')], default=0)),
                ('count', models.PositiveIntegerField(default=1)),
                ('double', models.BooleanField(default=False)),
                ('meal', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='blog.bill')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.itemcategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='blog.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.PROTECT, to='blog.itemcategory'),
        ),
    ]
