# Generated by Django 3.2.6 on 2021-08-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='double',
        ),
        migrations.RemoveField(
            model_name='item',
            name='meal',
        ),
        migrations.AddField(
            model_name='order',
            name='double',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='meal',
            field=models.BooleanField(default=False),
        ),
    ]
