# Generated by Django 3.2.6 on 2021-09-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210829_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='purchase',
        ),
        migrations.AddField(
            model_name='bill',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='orders',
            field=models.ManyToManyField(related_name='bills', to='blog.Order'),
        ),
        migrations.AlterField(
            model_name='item',
            name='double_meal_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='double_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='meal_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='blog.item'),
        ),
    ]
