# Generated by Django 3.2.6 on 2021-09-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='delivery',
            field=models.PositiveIntegerField(choices=[(500, '500'), (1000, '1000'), (1500, '1500')]),
        ),
    ]
