# Generated by Django 3.2.6 on 2021-09-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_inventory'),
        ('blog', '0004_auto_20210904_1752'),
    ]

    operations = [
    ]
