# Generated by Django 3.2.6 on 2021-09-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_bill_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bread',
            field=models.PositiveIntegerField(choices=[(0, 'خبز'), (700, 'مقرنات')], default=0),
        ),
    ]
